language: bash

sudo: required
services:
- docker

env:
  global:
    # GOPHERDOME_TOKEN
    secure: m18CXQqBNQl4zn6yqyEyDsfLLrHIaxhKTqecf9AxTDpa2U5rGFPyvCJCBL01MOluQw+SMOxnAaaectUdpvqllSvgMfPNVrz6mQK7MamhDzDxTejfFwZqmfs3OYnpYhPZmNMW0kWhG8Yloh0nQ6V+Pv9UtjD681FDw9v86PDhFnvQR+Lt4KawFiletI+34LNrI4FNgun1Zk3YjXpzOt0NtbCU4IYlQIxC/ul3J6n1bjN/ghgSweBuXKt1utCDZKd7g2cdmxDDhvcWV/hUwwd44ZL/u3Ru+1NcOims3JqN0zM4BDpKZdiMgs6h4jGXgzy1ekv52fOvsS/347Ypq7QEQmYlDYkHEqod3QiGDmX12QwbKhgputvzS186NGQr4I/fMlcdxdlibFGcILvpaST0RQcRG1WYEHiQt3K2u+X3P8LtMo1kL0TzzGIwafLGvaZuPblsuzxsreksMoISuvggPMsR3vWO3k1ThvQwZshnSm6hlAevpcn/bbNaYx0VnRbXPfV0j66iFw/JPpypIK+SDDJa1kWb2KIV1oSK9G/jhEOISsFFt6iNUooroR5+CzR5+KSYlaY7nOEjry2IG8+njcw8m5bEYMJYZOtGWfdnW0D70/rDjn51gpM4uHeSSIt0KTWak+7cD0d5GQIVPObB7F4rVWIXEuU82Xcmu0DFFwI=

script: make all
